name: mkdocs-deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocs-with-pdf
      - run: mkdocs build
      - run: mkdocs gh-deploy --force
  
      - name: Archive documentation pdf
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: site/pdf/document.pdf